// Single source of truth for every CMS section's admin form/table: field
// list + type drives FieldRenderer, apiPath maps to the backend factory
// routes. Adding a new field here (matching the backend model) is enough —
// no new component needed.

export const singletonSections = [
  {
    key: 'site-settings',
    label: 'Site Settings',
    apiPath: '/site-settings',
    fields: [
      { name: 'logoUrl', label: 'Logo', type: 'image', uploadField: 'logo' },
      { name: 'email', label: 'Email', type: 'text', required: true },
      { name: 'phone', label: 'Phone', type: 'text', required: true },
      { name: 'address', label: 'Address', type: 'text', required: true },
      { name: 'tagline', label: 'Footer tagline', type: 'textarea' },
      { name: 'slogan', label: 'Footer slogan', type: 'text' },
      {
        name: 'socialLinks',
        label: 'Social links',
        type: 'group',
        fields: [
          { name: 'linkedin', label: 'LinkedIn' },
          { name: 'facebook', label: 'Facebook' },
          { name: 'instagram', label: 'Instagram' },
          { name: 'youtube', label: 'YouTube' },
        ],
      },
      { name: 'copyrightText', label: 'Copyright text', type: 'text' },
    ],
  },
  {
    key: 'stats',
    label: 'Key Figures (Stats)',
    apiPath: '/stats',
    fields: [
      { name: 'clientsServed', label: 'Clients Served', type: 'number' },
      { name: 'projectsCompleted', label: 'Projects Completed', type: 'number' },
      { name: 'studentsMembers', label: 'Students & Members', type: 'number' },
      { name: 'formerCollaborators', label: 'Former Collaborators', type: 'number' },
      { name: 'juniorEnterprisesCount', label: 'Junior Enterprises', type: 'number' },
      { name: 'institutionalPartnersCount', label: 'Institutional Partners', type: 'number' },
      { name: 'newsFollowers', label: 'News Followers', type: 'number' },
      { name: 'newsletterSubscribers', label: 'Newsletter Subscribers', type: 'number' },
    ],
  },
  {
    key: 'home-content',
    label: 'Home Page',
    apiPath: '/home-content',
    fields: [
      { name: 'heroSince', label: 'Hero eyebrow (e.g. "Since 2006")', type: 'text' },
      { name: 'heroTitle', label: 'Hero title', type: 'text' },
      { name: 'heroSubtitle', label: 'Hero subtitle', type: 'text' },
      { name: 'whoWeAreTitle', label: '"Who we are" title', type: 'text' },
      { name: 'whoWeAreText', label: '"Who we are" text', type: 'textarea' },
      { name: 'yearsOfExperience', label: 'Years of experience', type: 'number' },
      { name: 'projectsCompletedLabel', label: 'Projects-completed label', type: 'text' },
      { name: 'ctaTitle', label: 'Call-to-action title', type: 'text' },
      { name: 'ctaText', label: 'Call-to-action text', type: 'textarea' },
    ],
  },
  {
    key: 'about-content',
    label: 'About Page',
    apiPath: '/about-content',
    fields: [
      { name: 'heroTitle', label: 'Hero title', type: 'text' },
      { name: 'heroSubtitle', label: 'Hero subtitle', type: 'text' },
      { name: 'introText', label: '"Who are we?" text', type: 'textarea' },
      { name: 'galleryImages', label: 'Rotating gallery images', type: 'imageList', uploadSubdir: 'about' },
    ],
  },
  {
    key: 'services-content',
    label: 'Services Page',
    apiPath: '/services-content',
    fields: [
      { name: 'heroTitle', label: 'Hero title', type: 'text' },
      { name: 'heroSubtitle', label: 'Hero subtitle', type: 'textarea' },
      { name: 'portfolioFileUrl', label: 'Portfolio PDF', type: 'pdf', uploadField: 'portfolio' },
    ],
  },
  {
    key: 'news-content',
    label: 'News Page',
    apiPath: '/news-content',
    fields: [
      { name: 'heroTitle', label: 'Hero title', type: 'text' },
      { name: 'heroSubtitle', label: 'Hero subtitle', type: 'textarea' },
    ],
  },
]

export const listSections = [
  {
    key: 'board-members',
    label: 'Board Members',
    apiPath: '/board-members',
    priority: true,
    titleField: 'name',
    subtitleField: 'role',
    thumbnailField: 'photoUrl',
    fields: [
      { name: 'photoUrl', label: 'Photo', type: 'image', uploadField: 'photo', required: true },
      { name: 'name', label: 'Full name', type: 'text', required: true },
      { name: 'role', label: 'Role', type: 'text', required: true },
      { name: 'mandateYear', label: 'Mandate year', type: 'number' },
    ],
  },
  {
    key: 'timeline-events',
    label: 'Timeline (About History)',
    apiPath: '/timeline-events',
    titleField: 'title',
    subtitleField: 'year',
    fields: [
      { name: 'year', label: 'Year', type: 'text', required: true },
      { name: 'title', label: 'Title', type: 'text', required: true },
      { name: 'description', label: 'Description', type: 'textarea' },
    ],
  },
  {
    key: 'values',
    label: 'Our Values (About)',
    apiPath: '/values',
    titleField: 'name',
    fields: [
      { name: 'name', label: 'Name', type: 'text', required: true },
      { name: 'description', label: 'Description', type: 'textarea' },
    ],
  },
  {
    key: 'divisions',
    label: 'Divisions (About)',
    apiPath: '/divisions',
    titleField: 'name',
    thumbnailField: 'iconUrl',
    fields: [
      { name: 'iconUrl', label: 'Icon', type: 'image', uploadField: 'icon' },
      { name: 'name', label: 'Name', type: 'text', required: true },
      { name: 'description', label: 'Description', type: 'textarea' },
    ],
  },
  {
    key: 'principles',
    label: 'Principles (Home)',
    apiPath: '/principles',
    titleField: 'name',
    thumbnailField: 'iconUrl',
    fields: [
      { name: 'iconUrl', label: 'Icon', type: 'image', uploadField: 'icon' },
      { name: 'name', label: 'Name', type: 'text', required: true },
      { name: 'description', label: 'Description', type: 'textarea' },
    ],
  },
  {
    key: 'service-categories',
    label: 'Service Categories',
    apiPath: '/service-categories',
    titleField: 'name',
    thumbnailField: 'iconUrl',
    fields: [
      { name: 'iconUrl', label: 'Icon', type: 'image', uploadField: 'icon' },
      { name: 'image', label: 'Detail image', type: 'image', uploadField: 'image' },
      { name: 'name', label: 'Name', type: 'text', required: true },
      { name: 'shortDescription', label: 'Short description (Home preview)', type: 'textarea' },
      { name: 'longDescription', label: 'Long description (Services page)', type: 'textarea' },
      { name: 'bulletPoints', label: 'Bullet points', type: 'stringList' },
    ],
  },
  {
    key: 'partners',
    label: 'Partners',
    apiPath: '/partners',
    titleField: 'name',
    thumbnailField: 'logoUrl',
    fields: [
      { name: 'logoUrl', label: 'Logo', type: 'image', uploadField: 'logo', required: true },
      { name: 'name', label: 'Name', type: 'text', required: true },
    ],
  },
  {
    key: 'events',
    label: 'Events',
    apiPath: '/events',
    titleField: 'name',
    subtitleField: 'category',
    fields: [
      { name: 'images', label: 'Images', type: 'imageList', uploadSubdir: 'events' },
      { name: 'name', label: 'Name', type: 'text', required: true },
      { name: 'category', label: 'Category / tag', type: 'text' },
      { name: 'description', label: 'Description', type: 'textarea' },
      { name: 'date', label: 'Date', type: 'date' },
      { name: 'location', label: 'Location', type: 'text' },
      { name: 'isMajor', label: 'Feature as the major event', type: 'checkbox' },
      { name: 'participants', label: 'Participants', type: 'number' },
      { name: 'speakers', label: 'Speakers', type: 'number' },
      { name: 'editions', label: 'Editions', type: 'number' },
      { name: 'link', label: 'Link URL', type: 'text' },
      { name: 'linkLabel', label: 'Link button label', type: 'text' },
    ],
  },
  {
    key: 'articles',
    label: 'Articles & News',
    apiPath: '/articles',
    listQuery: '?limit=200',
    reorderable: false,
    priority: true,
    titleField: 'title',
    subtitleField: 'tag',
    thumbnailField: 'coverImage',
    fields: [
      { name: 'coverImage', label: 'Cover image', type: 'image', uploadField: 'cover', required: true },
      { name: 'title', label: 'Title', type: 'text', required: true },
      {
        name: 'type',
        label: 'Feed',
        type: 'select',
        options: [
          { value: 'chronicle', label: 'Chronicle (long-form article)' },
          { value: 'news', label: 'News (short blurb)' },
        ],
      },
      { name: 'tag', label: 'Tag (e.g. "Analysis")', type: 'text', required: true },
      { name: 'excerpt', label: 'Excerpt', type: 'textarea', required: true },
      { name: 'content', label: 'Full content (optional, for self-hosted articles)', type: 'textarea' },
      { name: 'externalUrl', label: 'External link (e.g. LinkedIn) — leave blank if self-hosted', type: 'text' },
      { name: 'readTimeMinutes', label: 'Read time (minutes)', type: 'number' },
      { name: 'featured', label: 'Feature on News page front slot', type: 'checkbox' },
      { name: 'publishedAt', label: 'Published date', type: 'date' },
    ],
  },
  {
    key: 'magazines',
    label: 'Magazines',
    apiPath: '/magazines',
    reorderable: false,
    priority: true,
    titleField: 'title',
    subtitleField: 'number',
    thumbnailField: 'coverImage',
    fields: [
      { name: 'coverImage', label: 'Cover image', type: 'image', uploadField: 'cover', required: true },
      { name: 'fileUrl', label: 'PDF file', type: 'pdf', uploadField: 'file' },
      { name: 'number', label: 'Issue number (e.g. "N°12")', type: 'text', required: true },
      { name: 'pages', label: 'Page count', type: 'number', required: true },
      { name: 'title', label: 'Title', type: 'text', required: true },
      { name: 'description', label: 'Description', type: 'textarea', required: true },
      { name: 'publishedAt', label: 'Published date', type: 'date' },
    ],
  },
  {
    key: 'legal-documents',
    label: 'Legal Documents',
    apiPath: '/legal-documents',
    titleField: 'name',
    subtitleField: 'type',
    fields: [
      { name: 'fileUrl', label: 'PDF file', type: 'pdf', uploadField: 'file', required: true },
      { name: 'name', label: 'Name', type: 'text', required: true },
      { name: 'type', label: 'Type (e.g. "statuts")', type: 'text' },
    ],
  },
]
